
        <div class="footer content">
            <ul class="footer links">
                <li class="nav item"><a href="http://52.55.237.50/caricraft/privacy-policy-cookie-restriction-mode/">Privacy and Cookie Policy</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/sales/guest/form/">Orders and Returns</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/search/term/popular/">Search Terms</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/catalogsearch/advanced/" data-action="advanced-search">Advanced Search</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/contact/">Contact Us</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/blog/">Blog</a>
                </li>
                <li class="nav item"><a href="http://52.55.237.50/caricraft/selling-on-caricraft/">Selling on Caricraft</a>
                </li>
            </ul>
            <div class="block newsletter">
                <div class="title"><strong>Subscribe with us</strong>
                </div>
                <div class="content">
                    <form class="form subscribe" novalidate action="http://52.55.237.50/caricraft/newsletter/subscriber/new/" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
                        <div class="field newsletter">
                            <label class="label" for="newsletter"><span>Sign Up for Our Newsletter:</span>
                            </label>
                            <div class="control">
                                <input name="email" type="email" id="newsletter" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}" />
                            </div>
                        </div>
                        <div class="actions">
                            <button class="action subscribe primary" title="Subscribe" type="submit">
                                <span>Subscribe</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="payment_div">
                <ul>
                    <li class="visa"><span>Visa</span>
                    </li>
                    <li class="master-card"><span>Master Card</span>
                    </li>
                    <li class="paypal"><span>Paypal</span>
                    </li>
                    <li class="dhl"><span>DHL</span>
                    </li>
                    <li class="fac"><span><img src="http://52.55.237.50/caricraft/pub/media/wysiwyg/Powered-by-FAC_web.jpg" alt="Powered by FAC" /></span>
                    </li>
                </ul>
            </div>
            <div class="footer_social"><span>Connect us with</span>
                <ul class="social">
                    <li><a class="social-fb-link" href="javascript:void(0);"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a class="social-twt-link" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a class="social-gp-link" href="javascript:void(0);"><i class="fa fa-google-plus"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>

    <small class="copyright">
        <span>Copyright © 2016 Caricraft.com. All rights reserved.</span>
    </small>
