<?php // echo 'This is the Simple Welcome Module in Magento 2.0';?>
<?php // echo $block->dckWelcome(); ?>
<!--<div class="footer_social">
<span>Connect us with</span>
<ul class="social">
<li>
<a class="social-fb-link" href="javascript:void(0);"> <i class="fa fa-facebook"></i></a></li>
<li>
<a class="social-twt-link" href="javascript:void(0);"> <i class="fa fa-twitter"></i></a></li>
</ul>
</div> -->
<div class="footer-social">
<span>Connect us with</span></br>
<ul class="social">
<li><a class="social-fb-link" href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
<li><a class="social-twt-link" href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
<li><a class="social-gp-link" href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
</ul>
</div>
